name: dart_breakout
version: "0.3.0"
description: dart breakout clone because
author: Harry Stern <harry.stern@rutgers.edu>
homepage: https://github.com/boustrophedon/dart-breakout
environment:
    sdk: '>=2.0.0 <3.0.0'

dependencies:
  entity_component:
      git:
        url: git://github.com/boustrophedon/entity-component-dart.git

dev_dependencies:
    build_runner: ^1.1.2
    build_web_compilers: ^1.0.0

