name: dart_breakout
version: "0.3.0"
description: dart breakout clone because
author: Harry Stern <harry.stern@rutgers.edu>
homepage: https://github.com/boustrophedon/dart-breakout
environment:
  sdk: ">=1.8.0"
dependencies:
  browser: any
  entity_component:
    git:
      url: git://github.com/boustrophedon/entity-component-dart.git
      ref: ng
